apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: node
spec:
  project: default
  source:
    chart: node-hello
    repoURL: registry-1.docker.io/ayushi0316
    targetRevision: 0.1.1
    helm: 
      releaseName: node-hello
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"