app:
  name: app
  group: app
  replicaCount: 1
  container:
    image: ayushi0316/node_hello:latest
    port: 3000
    config: []
    env:
       - key: key
         value: value
  service:
    type: ClusterIP
    port: 80